baseURL = "https://alicereuter.com/"
languageCode = "en-us"
title = "Alice Reuter"
theme = "solar-theme-hugo"
pygmentsCodeFences = true
pygmentsUseClasses = true
disableHugoGeneratorInject = true
[params]
  description = "TAGLINE"
  offset = "OFFSET"
  bios = "I'm second year CS Student at the University of Texas at Austin. I like to pen test and do reversing."


[markup]
  defaultMarkdownHandler = "blackfriday"


[menu]
  [[menu.a]]
    name="home"
    url="/"
  [[menu.b]]
    name="email"
    url="mailto:alice@alicereuter.com"
  [[menu.github]]
    name="github"
    url="https://github.com/alicelambda"
