baseURL = "https://alicereuter.com/"
languageCode = "en-us"
title = "Alice Reuter"
theme = "solar-theme-hugo"
pygmentsCodeFences = true
pygmentsUseClasses = true
disableHugoGeneratorInject = true
googleAnalytics = "UA-140668376-1"

[params]
  offset = "OFFSET"
  bios = "I'm second year CS Student at the University of Texas at Austin. I like to pen test and do reversing."


[markup]
  defaultMarkdownHandler = "blackfriday"


[menu]
  [[menu.a]]
    name="Home"
    url="/"
  [[menu.b]]
    name="Email"
    url="mailto:alice@alicereuter.com"
  [[menu.github]]
    name="Github"
    url="https://github.com/alicelambda"
